### ISSUE TITLE
Open 1 issue for each known error in historical data

### ISSUE THREAD

**Issue by RachelePoggi** [transportenergy/database#56]
Hello!
Could you please list the problems you encountered in ITF historical series?
thank you

**Comment by khaeru** [comment]
All, it would be good to open individual issues like #47 for each of these. Possibly some can be fixed quickly, and others will take more time. It also continues the pattern that we will use for more issues discovered later (after we've fixed the ones we know about currently).

Once those are all opened, we can simply link to them each from here, and then close this one. We might even change this one's title to “**Open** 1 issue for each known error in historical data” to precisely describe the task to be completed.

**Comment by soniayeh** [comment]
Thanks for the suggestion. It is quite okay. I will post the list here then we can open individual issues for each one on the list that needs to be dealt with individually.

**Comment by hlinero** [comment]
Opening an issue for each known error.

**Comment by khaeru** [comment]
@hlinero I see that #60 and #61 were opened. Are these the *only* upstream data issues in all of the identified input data sets, up to T010 inclusive? If not, we should leave this meta-issue opened until it is actually complete.
