### ISSUE TITLE
Mode & Vehicle Type values missing when running historical.process()

### ISSUE THREAD

**Issue by francescolovat** [transportenergy/database#69]
Hi iTEM colleagues,

I'm raising this issue since recent usages of `process.historical(0)` (T000) and `process.historical(4)` (T004) led to `NaN`s in the resulting dataframe columns `Mode` & `Vehicle Type` (for the former) and `Vehicle Type` in the case of the latter.

Values seem to be present in the `.csv` files, so this might come from the processing scripts, unless I'm missing something.

![pic-1](https://user-images.githubusercontent.com/56022262/115604523-c4eade00-a2e1-11eb-9dac-6a2b3e19f172.png)
![pic-2](https://user-images.githubusercontent.com/56022262/115604521-c4eade00-a2e1-11eb-9eff-a846c28672de.png)

**Comment by soniayeh** [comment]
It seems like a code issue. I am not using the code, but the final spreadsheet that Humberto generated for me from his codes. 
![fig](https://user-images.githubusercontent.com/20838755/115735277-a4c32980-a38a-11eb-92f6-7642e031cb98.jpg)

You are right that "nan" should not be there. They should be ALL. see attached.

**Comment by khaeru** [comment]
@francescolovat good catch.

The best way to address this will be a consistency check, that gets run on the cleaning script for each of the upstream data sources.

**Comment by khaeru** [comment]
Thanks @francescolovat for opening #72. This will be closed by #71, which adds the consistency checks I mentioned:

> The best way to address this will be a consistency check, that gets run on the cleaning script for each of the upstream data sources.

…along with other improvements, namely avoiding the use of easily-confused column names (either via the older `ColumnName` enumeration or the newer `column_name()` function) and simply using everywhere the consistent IDs of the SDMX dimensions introduced by #62.
This has the advantage of associating the column labels to the SDMX concepts with the same IDs, and those can have long & verbose names and descriptions; longer than would be practical to stick in a column label.

**Comment by francescolovat** [comment]
Thank you, @khaeru!
