### ISSUE TITLE
Is this repository active, or is there a fork somewhere?

### ISSUE THREAD

**Issue by paulterinho** [transportenergy/database#77]
Hi all, just curious if this repository is still being maintained, or perhaps there is a fork somewhere that is being used instead (looks like the last update was 2 years ago)?

**Comment by soniayeh** [comment]
Hi Paul, indeed we have been very quiet due to the lack of funding. Now we have a few students working on it as their degree project as you might start seeing more activity in the coming weeks. Is there any specific thing you would like to see/do?

**Comment by paulterinho** [comment]
Hi Dr. Yeh, ahhh, that makes sense. Just making sure it was viable, thanks for the update!
